### ISSUE TITLE
Won't retain default option after 4.7

### ISSUE THREAD

**Issue by cschack** [rwetzlmayr/wet_textfilter_markdown#3]
After I upgraded to TXP 4.7, you can't set markdown as the default text option. If you set markdown manually on a per-post basis, it works, so it's more of a frustration than a major problem, but still.

**Comment by craigbass76** [comment]
Ahh, I'm new and I was looking for a way to make it default (check box somewhere that I missed or something). Guess I'm out of luck for now...

**Comment by danlei** [comment]
Works for me on 4.8.5/PHP 7.4.

**Comment by cschack** [comment]
I realized I'd forgotten about this, but it works for me now. :)
